version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: zenithpass-db
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # API Gateway
  api_gateway:
    build:
      context: ./zenithpass/apps/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db

  # Register Service
  register_service:
    build:
      context: ./zenithpass/apps/register-service
      dockerfile: Dockerfile
    container_name: register-service
    ports:
      - "3001:3000"
    depends_on:
      - postgres_db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${POSTGRES_DB}

volumes:
  postgres_data:
